import React, { useState } from 'react';
import { FaIdCard, FaSignOutAlt, FaSyncAlt, FaPrint, FaDownload } from 'react-icons/fa';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { useNavigate } from 'react-router-dom'; // ✅ import navigation

import logo from '../assets/images/logo.png';
import frontId from '../assets/images/1 FRONT.png';
import backId from '../assets/images/1 BACK.png';

const Viewing = () => {
  const [flipped, setFlipped] = useState(false);
  const navigate = useNavigate(); // ✅ initialize

  const handleFlip = () => {
    setFlipped(!flipped);
  };

  // ✅ Print only front and back IDs
  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Print ID</title>
          <style>
            body {
              display: flex;
              justify-content: center;
              align-items: center;
              gap: 20px;
              padding: 20px;
            }
            img {
              width: 300px;
              height: 500px;
              object-fit: cover;
              border-radius: 12px;
              box-shadow: 0 4px 8px rgba(0,0,0,0.2);
            }
          </style>
        </head>
        <body>
          <img src="${frontId}" alt="Front ID"/>
          <img src="${backId}" alt="Back ID"/>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  };

  // ✅ Download both front and back IDs as a zip
  const handleDownload = async () => {
    const zip = new JSZip();
    const folder = zip.folder('ID-Cards');

    const toBlob = async (url) => {
      const response = await fetch(url);
      return await response.blob();
    };

    folder.file('front-id.png', await toBlob(frontId));
    folder.file('back-id.png', await toBlob(backId));

    const content = await zip.generateAsync({ type: 'blob' });
    saveAs(content, 'ID-Cards.zip');
  };

  // ✅ Logout → redirect to Login2 page (/viewidlogin)
  const handleLogout = () => {
    navigate('/viewidlogin', { replace: true });
  };

  return (
    <div className="flex h-screen">
      {/* Sidebar */}
      <div className="group w-16 hover:w-48 transition-all duration-300 bg-[#2f2651] text-white flex flex-col justify-between py-6 px-2 overflow-hidden">
        {/* Top Section */}
        <div>
          {/* Logo and Brand */}
          <div className="flex items-center gap-2 mb-10 px-1">
            <img src={logo} alt="Logo" className="w-8 h-8" />
            <span className="text-white font-bold text-sm tracking-wide opacity-0 group-hover:opacity-100 transition duration-200 whitespace-nowrap">
              IT Squarehub
            </span>
          </div>

          {/* View ID Button */}
          <button className="flex items-center gap-2 w-full px-3 py-2 rounded-lg text-sm font-medium hover:bg-[#4c4370] transition">
            <FaIdCard className="text-base min-w-[20px]" />
            <span className="opacity-0 group-hover:opacity-100 transition duration-200 whitespace-nowrap">
              View ID
            </span>
          </button>
        </div>

        {/* ✅ Logout Button */}
        <button
          onClick={handleLogout}
          className="flex items-center gap-2 w-full px-3 py-2 rounded-lg text-sm font-medium hover:bg-[#4c4370] transition"
        >
          <FaSignOutAlt className="text-base min-w-[20px]" />
          <span className="opacity-0 group-hover:opacity-100 transition duration-200 whitespace-nowrap">
            Logout
          </span>
        </button>
      </div>

      {/* Main Content */}
      <div className="flex-1 bg-gradient-to-b from-purple-200 via-purple-300 to-purple-700 flex items-center justify-center">
        <div className="flex flex-col md:flex-row items-center gap-8">
          {/* ID Card */}
          <div
            className="bg-white rounded-md shadow-xl overflow-hidden"
            style={{ width: '300px', height: '500px' }}
          >
            <img
              src={flipped ? backId : frontId}
              alt="ID Card"
              className="w-full h-full object-cover"
            />
          </div>

          {/* Info + Buttons */}
          <div className="flex flex-col gap-4">
            <div className="bg-white p-4 rounded-lg shadow-md w-72">
              <p className="font-semibold">
                Generated by: <span className="font-normal">John Doe</span>
              </p>
              <p>Email: johndoegnhut@gmail.com</p>
            </div>

            <div className="bg-white p-4 rounded-lg shadow-md w-72">
              <p className="font-semibold">
                Approved by: <span className="font-normal">Jane Doe</span>
              </p>
              <p>Email: janedoegnhut@gmail.com</p>
            </div>

            {/* Action Buttons */}
            <div className="flex gap-3">
              <button
                onClick={handleFlip}
                className="flex items-center gap-2 text-sm px-4 py-2 bg-white rounded-lg shadow-md hover:bg-gray-100 transition"
              >
                <FaSyncAlt /> Flip ID
              </button>
              <button
                onClick={handlePrint}
                className="flex items-center gap-2 text-sm px-4 py-2 bg-white rounded-lg shadow-md hover:bg-gray-100 transition"
              >
                <FaPrint /> Print
              </button>
              <button
                onClick={handleDownload}
                className="flex items-center gap-2 text-sm px-4 py-2 bg-white rounded-lg shadow-md hover:bg-gray-100 transition"
              >
                <FaDownload /> Download
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Viewing;
